auth:
  BOT_TOKEN: "NjY2NjYxNDMyODAwMTgyMjk1.XiGzlQ.6BHy20iEJYalYzEimRZpRqBn8ss"
  CLIENT_ID: "666661432800182295"
  SENTRY_URL: "https://84a901d830004169b92656fc9006957e@o342182.ingest.sentry.io/5481121"

db:
  PGHOST: "ec2-54-247-188-107.eu-west-1.compute.amazonaws.com"
  PGPORT: 5432
  PGDATABASE: "d3b79dcek72n50"
  PGUSER: "orxdncqlpnqtdd"
  PGPASSWORD: "0dfcd5d4ebf978dd3eff30d1547fafcd765eaadf2c88c6735dd04aeae5cf5d65"

api_keys:
  tenor: "66LHN02QKD2B"

bot_settings:
  # name of the logger
  logger_name: "Qutils"
  # log level of the bot
  log_level: "DEBUG"
  owner_ids: [647577161200566289]

guilds:
 - ID: 648262260724203523
   PREFIX: ["?"]
   channels:
      LOGGING_CHANNEL_ID: 648867664026009621
      ANNOUNCEMENT_CHANNEL_ID: 653301549979795467
      CONFESSION_CHANNEL_ID: 750452002248458330
      RECEPTION_CHANNEL_ID: 648623592828960768
      ADMIN_CHANNEL_ID: 653695277605322761
      FEEDBACK_CHANNEL_ID: 653589800418410527
      GENERAL_CHAT_CHANNEL_ID: 653589800418410527
   roles:
     HELPER_ROLES:
       # role given for newcomers who not approved and waiting in a reception
       STRANGER_ROLE: {ID: &stranger_role_id 648628529482825738}
       # role given to bots
       BOT_ROLE: {ID: &bot_role_id 651926730918854657}
       # role given to active members in the server
       ACTIVE_ROLE: {ID: 651924241867997204}
       # role given to members with very best stats
       LEADER_ROLE: {ID: 659037604284727297}
     # role hierarchy in the server use for levelling system
     HIERARCHY_ROLES:
       # Çaylaklar
       5: {ID: &rookies_role_id 648264430089404437, TONEXT: 60, NEXTID: 653293626780024893}
       # Tecrübeliler
       4: {ID: &veterans_role_id 653293626780024893, TONEXT: 240, NEXTID: 648262844089106453}
       # Müdavimler
       3: {ID: &regulars_role_id 648262844089106453, TONEXT: null, NEXTID: null}
       # Yönetim
       2: {ID: &admins_role_id 648262492317024317, TONEXT: null, NEXTID: null}
       # Sahip
       1: {ID: &owner_role_id 648262710990995467, TONEXT: null, NEXTID: null}
     # roles given to members by sexual orientation in the server
     GENDER_ROLES: [672911842632532001, 672911708083191851, 672912027840282632]
   cogs:
     # common settings for all cogs
     # all main guild roles including bot and stranger role
     all_guild_roles: [*stranger_role_id, *bot_role_id, *rookies_role_id, *veterans_role_id,
                       *regulars_role_id, *admins_role_id, *owner_role_id ]
     # all valid roles excluding bot role and stranger role
     all_valid_roles: [*rookies_role_id, *veterans_role_id, *regulars_role_id,
                       *admins_role_id, *owner_role_id ]
     # all guild roles responsible for sustaining the active role
     activity_included_roles: [*rookies_role_id, *veterans_role_id ]
     # all admin roles for this guild
     admin_roles: [*owner_role_id, *admins_role_id]
     # various delay value for operations such as message deletion etc.
     short_delay: 60
     mid_delay: 120
     long_delay: 300
     general:
       # minimum number of needed days removing inactive members after last prune
       activity_schedule_gap: '5d'
       # number of days for checking role upgrade
       role_upgrade_gap: '1d'
       # minimum number of days passed since a member joined to be effected by activity removal rule
       activity_min_day: 7
       # directory for json permission templates
       base_json_dir: 'json_templates'
       # text template for inactive member announcement
       activity_template: |
         {} tarihine kadar aktiflik sartini saglamaz veya yonetime mazeret
         bildirmez ise cikartilacak uye listesi
       # text template sent to inactive members in pm channel
       activity_pm_template: |
         Bu mesajı sana {} dan gönderiyorum.
         Artık seni aramızda sık sık göremiyoruz ve bu bizi çok üzüyor 😔 .
         Aktiflik rolüne sahip olmadığın için seni atılacak üye listesine ekledik.
         Eğer {} tarihine kadar aktif rolünü kazanmazsan veya yönetime eksikliğinin
         mazeretini bildirmez isen maalesef seni yukarıdaki tarihte kanaldan atmak zorunda kalacağım 😢 .
       # text template to send removed inactive members to rejoin if they would like to
       removed_member_pm_template:
         Tekrar merhaba! Aktiflik rolünü daha önce belirtilen tarihe kadar
         kazanamadığın için {} sunucusundan çıkartıldın. Ama bu herşeyin sonu demek değil.
         Senin için yeni bir davet oluşturdum, işte burda; { } \n Bu davet linki ile istersen
         bize tekrar katılabilirsin, unutma bu davet sadece {} gün geçerli olacak.
         Davete tıklayıp yeniden kanala katıldığında bu sefer aktif olacağına
         dair bana söz vermiş olacaksın, unutma!!!
       # text template to send after hierarchy role upgrade
       role_upgrade_template: "Tebrikler {}! {} rolunden {} rolune yukseldin!"
     confession:
       # number of seconds to timeout typing confession message
       message_timeout: 600
       # number of times a member has been warned before ban
       warn_limit: 3
       # number of seconds needs in between two consecutive confession creation
       command_cooldown: 6000
       # role ids valid for creating new confessions
       valid_confession_roles: [ *veterans_role_id, *regulars_role_id,
                                 *admins_role_id, *owner_role_id ]
     camdice:
       # max number of members will be lost a camdice game
       max_lost_member: 4
       # number of seconds to wait to read instructions before game starts
       start_game_delay: 2
     truthdare:
       # directory for fetching truth and dare questions
       base_truthdare_dir: 'truthdare'
     automation:
       # number of days the inactive members will be announced in announcement channel
       num_announce_days: 2
       # text template used for announcing inactive members before pruning
       announcement_template: |
         Maalesef aşağıda listelenen üyelerimiz kanalın aktiflik şartını sağlayamadıkları
         için **{}** rolüne sahip değiller. **{}** rolüne sahip olmayan bu üyeler olası bir aktif
         olmayan üyeleri çıkarma işleminde kanaldan **ATILACAKLARDIR!!!** Bu üyelerden ricamız
         lütfen en kısa sürede kanalda yeterince aktif olmaya başlamalarıdır.\n
         ** *Aşağıda mazeretlerini bildiren üyeler listelenmiştir,
         lütfen bu üyeler duyuruyu dikkate almasın.
         Bu üyeler haricinde eğer geçici bir mazeretiniz varsa lütfen yönetime bildirin.* ** \n
         ***Aktiflik şartı: https://sites.google.com/view/nightzone/ana-sayfa#h.p_6i1CL4wFpmQV***\n