#!/usr/bin/env bash
# this script mainly created for overcaming the problem of activating conda environment in Heroku

source /opt/conda/etc/profile.d/conda.sh
conda activate "$(head -1 ./environment.yml | cut -d' ' -f2)"
python launcher.py